services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_msv
    environment:
      - cluster.name=opensearch-cluster-msv
      - node.name=opensearch-node-msv
      - discovery.type=single-node
      # УДАЛИТЬ ЭТУ СТРОКУ: - cluster.initial_cluster_manager_nodes=opensearch-node-msv
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data-msv:/usr/share/opensearch/data
    ports:
      - "9212:9200"
      - "9600:9600"
    networks:
      - opensearch-net-msv
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards_msv
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - "5612:5601"
    networks:
      - opensearch-net-msv
    restart: unless-stopped
    depends_on:
      - opensearch

volumes:
  opensearch-data-msv:

networks:
  opensearch-net-msv: